{ config, pkgs, lib, ... }:

with lib;

let
  cfg = config.modules.swaylock;
in
{
  options.modules.swaylock = {
    enable = mkEnableOption "Swaylock screen locker";

    indicator = {
      radius = mkOption {
        type = types.int;
        default = 120;
        description = "Radius of the indicator circle";
      };

      thickness = mkOption {
        type = types.int;
        default = 0;
        description = "Thickness of the indicator ring (0 = no ring)";
      };
    };

    colors = {
      background = mkOption {
        type = types.str;
        default = "00000000";
        description = "Background color - transparent (hex without #)";
      };

      text = mkOption {
        type = types.str;
        default = "e0def4";
        description = "Text color - matches hyprlock light gray (hex without #)";
      };

      ring = mkOption {
        type = types.str;
        default = "00000000";
        description = "Ring color - transparent (no ring) (hex without #)";
      };

      ringVer = mkOption {
        type = types.str;
        default = "00000000";
        description = "Ring color during verification - transparent (hex without #)";
      };

      ringWrong = mkOption {
        type = types.str;
        default = "ebbcba";
        description = "Ring color on wrong password - peachy (hex without #)";
      };

      key = mkOption {
        type = types.str;
        default = "9ccfd8";
        description = "Highlight color for key press - cyan (hex without #)";
      };

      separator = mkOption {
        type = types.str;
        default = "00000000";
        description = "Separator color - transparent (hex without #)";
      };

      inside = mkOption {
        type = types.str;
        default = "00000080";
        description = "Inside color - semi-transparent black like hyprlock (hex without #)";
      };

      insideVer = mkOption {
        type = types.str;
        default = "00000080";
        description = "Inside color during verification (hex without #)";
      };

      insideWrong = mkOption {
        type = types.str;
        default = "00000080";
        description = "Inside color on wrong password (hex without #)";
      };
    };

    font = {
      family = mkOption {
        type = types.str;
        default = "JetBrains Mono Nerd Font";
        description = "Font family";
      };

      size = mkOption {
        type = types.int;
        default = 24;
        description = "Font size";
      };
    };

    image = {
      path = mkOption {
        type = types.str;
        default = "${config.wallpaperDir}/${cfg.image.fileName}";
        description = "Path to background image";
      };

      fileName = mkOption {
        type = types.str;
        default = "cat_lofi_cafe.jpg";
        description = "Filename of the wallpaper in the global wallpaper directory";
      };

      scaling = mkOption {
        type = types.enum [ "fill" "fit" "center" "tile" "solid_color" ];
        default = "fill";
        description = "Image scaling mode";
      };
    };

    effects = {
      fadeIn = mkOption {
        type = types.float;
        default = 0.2;
        description = "Fade in time in seconds";
      };

      blur = mkOption {
        type = types.str;
        default = "5x3";
        description = "Blur effect (format: radiusxpasses)";
      };

      clock = mkOption {
        type = types.bool;
        default = true;
        description = "Show clock on lock screen";
      };

      indicator = mkOption {
        type = types.bool;
        default = true;
        description = "Show indicator";
      };

      screenshots = mkOption {
        type = types.bool;
        default = false;
        description = "Allow taking screenshots while locked";
      };
    };

    text = {
      insideText = mkOption {
        type = types.str;
        default = "";
        description = "Text shown inside the indicator";
      };

      verifyingText = mkOption {
        type = types.str;
        default = "Verifying...";
        description = "Text shown during verification";
      };

      wrongText = mkOption {
        type = types.str;
        default = "Wrong!";
        description = "Text shown on wrong password";
      };

      noInputText = mkOption {
        type = types.str;
        default = "";
        description = "Text shown when input is empty";
      };
    };
  };

  config = mkIf cfg.enable {
    programs.swaylock = {
      enable = true;
      package = pkgs.swaylock-effects;
    };

    home.packages = with pkgs; [
      swaylock-effects
    ];

    xdg.configFile."swaylock/config".text = ''
      # Swaylock Configuration
      # Generated by NixOS Home Manager

      # Display options
      daemonize
      ${optionalString cfg.effects.clock "clock"}
      ${optionalString cfg.effects.indicator "indicator"}
      # ignore-empty-password removed to allow fingerprint-only authentication

      # Image and effects
      image=${cfg.image.path}
      scaling=${cfg.image.scaling}
      effect-blur=${cfg.effects.blur}
      fade-in=${toString cfg.effects.fadeIn}

      # Font configuration
      font=${cfg.font.family}
      font-size=${toString cfg.font.size}

      # Indicator sizing
      indicator-radius=${toString cfg.indicator.radius}
      indicator-thickness=${toString cfg.indicator.thickness}

      # Color configuration
      color=${cfg.colors.background}
      text-color=${cfg.colors.text}

      # Ring colors
      ring-color=${cfg.colors.ring}
      ring-ver-color=${cfg.colors.ringVer}
      ring-wrong-color=${cfg.colors.ringWrong}

      # Inside colors
      inside-color=${cfg.colors.inside}
      inside-ver-color=${cfg.colors.insideVer}
      inside-wrong-color=${cfg.colors.insideWrong}

      # Key and separator colors
      key-hl-color=${cfg.colors.key}
      separator-color=${cfg.colors.separator}

      # Border colors (matching ring)
      bs-hl-color=${cfg.colors.ringWrong}
      caps-lock-bs-hl-color=${cfg.colors.ringWrong}
      caps-lock-key-hl-color=${cfg.colors.key}

      # Line colors (transparent)
      line-color=00000000
      line-ver-color=00000000
      line-wrong-color=00000000
      line-clear-color=00000000
      line-caps-lock-color=00000000

      # Text strings
      text=${cfg.text.insideText}
      text-ver=${cfg.text.verifyingText}
      text-wrong=${cfg.text.wrongText}
      text-clear=${cfg.text.noInputText}
      text-caps-lock=Caps Lock

      # Time and date format (if clock is enabled)
      ${optionalString cfg.effects.clock ''
      timestr=%I:%M %p
      datestr=%A, %B %d
      ''}
    '';

    # Create a simple wrapper script for easier invocation
    home.file.".local/bin/lock".text = ''
      #!/usr/bin/env bash
      swaylock
    '';
    home.file.".local/bin/lock".executable = true;
  };
}
