{ config, pkgs, lib, ... }:

with lib;

let
  cfg = config.modules.swayidle;
in
{
  options.modules.swayidle = {
    enable = mkEnableOption "Swayidle idle daemon";

    timeouts = {
      lock = mkOption {
        type = types.int;
        default = 300;
        description = "Seconds of inactivity before locking (0 to disable)";
      };

      displayOff = mkOption {
        type = types.int;
        default = 600;
        description = "Seconds of inactivity before turning off display (0 to disable)";
      };

      suspend = mkOption {
        type = types.int;
        default = 900;
        description = "Seconds of inactivity before suspending (0 to disable)";
      };
    };

    commands = {
      lock = mkOption {
        type = types.str;
        default = "swaylock";
        description = "Command to run for locking";
      };

      unlock = mkOption {
        type = types.str;
        default = "";
        description = "Command to run after unlocking";
      };

      beforeSleep = mkOption {
        type = types.str;
        default = "swaylock";
        description = "Command to run before sleep";
      };

      afterResume = mkOption {
        type = types.str;
        default = "";
        description = "Command to run after resume";
      };

      displayOff = mkOption {
        type = types.str;
        default = "niri msg action power-off-monitors";
        description = "Command to turn off displays";
      };

      displayOn = mkOption {
        type = types.str;
        default = "";
        description = "Command to turn on displays (usually automatic)";
      };
    };

    extraIdleHints = mkOption {
      type = types.listOf types.str;
      default = [];
      description = "Additional idle hints for swayidle";
      example = [
        "timeout 30 'if pgrep -x swaylock; then niri msg action power-off-monitors; fi'"
      ];
    };
  };

  config = mkIf cfg.enable {
    home.packages = with pkgs; [
      swayidle
    ];

    # Create swayidle configuration
    xdg.configFile."swayidle/config".text =
      let
        # Build timeout commands
        lockTimeout = optionalString (cfg.timeouts.lock > 0)
          "timeout ${toString cfg.timeouts.lock} '${cfg.commands.lock}' ${optionalString (cfg.commands.unlock != "") "resume '${cfg.commands.unlock}'"}";

        displayTimeout = optionalString (cfg.timeouts.displayOff > 0)
          "timeout ${toString cfg.timeouts.displayOff} '${cfg.commands.displayOff}' ${optionalString (cfg.commands.displayOn != "") "resume '${cfg.commands.displayOn}'"}";

        suspendTimeout = optionalString (cfg.timeouts.suspend > 0)
          "timeout ${toString cfg.timeouts.suspend} 'systemctl suspend'";

        beforeSleepCmd = optionalString (cfg.commands.beforeSleep != "")
          "before-sleep '${cfg.commands.beforeSleep}'";

        afterResumeCmd = optionalString (cfg.commands.afterResume != "")
          "after-resume '${cfg.commands.afterResume}'";

        extraHints = concatStringsSep "\n" cfg.extraIdleHints;

        allCommands = concatStringsSep "\n" (filter (s: s != "") [
          lockTimeout
          displayTimeout
          suspendTimeout
          beforeSleepCmd
          afterResumeCmd
          extraHints
        ]);
      in
      ''
        # Swayidle Configuration
        # Generated by NixOS Home Manager

        ${allCommands}
      '';

    # Create systemd service for swayidle
    systemd.user.services.swayidle = {
      Unit = {
        Description = "Idle manager for Wayland";
        Documentation = "man:swayidle(1)";
        PartOf = [ "graphical-session.target" ];
        After = [ "graphical-session.target" ];
      };

      Service = {
        Type = "simple";
        ExecStart = "${pkgs.swayidle}/bin/swayidle -w";
        Restart = "on-failure";
        RestartSec = 1;
        TimeoutStopSec = 10;
      };

      Install = {
        WantedBy = [ "graphical-session.target" ];
      };
    };
  };
}